FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV MINIKUBE_VERSION=v1.36.0
ENV CRICTL_VERSION=v1.28.0

# Instalar dependências essenciais
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    gnupg \
    lsb-release \
    apt-transport-https \
    sudo \
    vim \
    git \
    nano \
    iptables \
    conntrack \
    socat \
    ebtables \
    iproute2 \
    systemd \
    && rm -rf /var/lib/apt/lists/*

# Instalar kubectl (última versão estável)
RUN KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt) && \
    curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# Instalar minikube
RUN curl -LO https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64 \
    && install -o root -g root -m 0755 minikube-linux-amd64 /usr/local/bin/minikube \
    && rm minikube-linux-amd64

# Instalar crictl
RUN curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz \
    && tar -C /usr/local/bin -xzvf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz \
    && rm crictl-${CRICTL_VERSION}-linux-amd64.tar.gz

# Comando padrão
CMD ["bash"]
RUN curl -LO https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64 \
    && install -o root -g root -m 0755 minikube-linux-amd64 /usr/local/bin/minikube \
    && rm minikube-linux-amd64

# Instalar crictl
RUN curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz \
    && tar -C /usr/local/bin -xzvf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz \
    && rm crictl-${CRICTL_VERSION}-linux-amd64.tar.gz

# Comando padrão
CMD ["bash"]